"""Shared constants for STAR-TAT."""

from __future__ import annotations

PROJECT_NAME = "P1_STAR_TAT"

# Run status values recorded in manifests. Historical runs carry
# INTERNAL_RESEARCH; EXTERNAL_VALIDATION is reserved for runs whose inputs
# and metrics are formed by an independent party.
RUN_STATUS_INTERNAL = "INTERNAL_RESEARCH"
RUN_STATUS_EXTERNAL = "EXTERNAL_VALIDATION"
RUN_STATUSES = (RUN_STATUS_INTERNAL, RUN_STATUS_EXTERNAL)

DECISION_OUTPUT = "OUTPUT"
DECISION_ABSTAIN = "ABSTAIN"
DECISIONS = (DECISION_OUTPUT, DECISION_ABSTAIN)

# Abstention reasons (P1 decision = ABSTAIN).
REASON_UNMAPPED_STAGE = "UNMAPPED_STAGE"
REASON_FEATURE_UNAVAILABLE = "FEATURE_UNAVAILABLE"
REASON_UNKNOWN_WORKFLOW_VERSION = "UNKNOWN_WORKFLOW_VERSION"
REASON_INSUFFICIENT_CALIBRATION = "INSUFFICIENT_CALIBRATION"
REASON_SHIFT_DETECTED = "SHIFT_DETECTED"
REASON_CODES = (
    REASON_UNMAPPED_STAGE,
    REASON_FEATURE_UNAVAILABLE,
    REASON_UNKNOWN_WORKFLOW_VERSION,
    REASON_INSUFFICIENT_CALIBRATION,
    REASON_SHIFT_DETECTED,
)

# Split block names.
BLOCK_TRAIN = "train"
BLOCK_CALIBRATION = "calibration"
BLOCK_HOLDOUT = "holdout"
BLOCKS = (BLOCK_TRAIN, BLOCK_CALIBRATION, BLOCK_HOLDOUT)

# Canonical stage chain. The order is frozen; it is never inferred from data.
CANONICAL_STAGES = (
    "SAMPLE_RECEIVED",
    "ACCESSIONED",
    "LIBRARY_PREPARED",
    "SEQUENCING_STARTED",
    "ANALYSIS_COMPLETE",
    "REVIEWED",
    "RELEASED",
)

STAGE_UNMAPPED = "UNMAPPED"
STAGE_NOT_COMPARABLE = "NOT_COMPARABLE"

# Exclusion reasons recorded in excluded_rows.csv during snapshot building.
EXCLUDE_LATE_KNOWN_EVENT = "LATE_KNOWN_EVENT"
EXCLUDE_FUTURE_SNAPSHOT = "FUTURE_LOAD_SNAPSHOT"
EXCLUDE_MISSING_CASE_ROW = "MISSING_CASE_ROW"
EXCLUDE_MISSING_CASE = EXCLUDE_MISSING_CASE_ROW
EXCLUDE_AFTER_RELEASE = "AS_OF_AFTER_RELEASE"
EXCLUDE_NO_TARGET = "NO_TARGET"
